server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
#  profiles:
#    active:
  application:
    name: eurekaclient

#
#---
#spring:
#  profiles: test
#---
#spring:
#  profiles: test2
#---
#spring:
#  profiles: test3